---
title: "Introduction"
author: "The methylation in ART meta-analysis group"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    fig_width: 7
    fig_height: 7
theme: cosmo
---

Source: https://github.com/markziemann/ART_methylation/introduction.Rmd

## Background

### What is ART?

Assisted reproductive technology (ART) is a group of medical procedures defined by the WHO to enable conception due to reduced fertility (Zegers-Hochschild et al, 2009)[1].
This includes in vitro fertilization (IVF), intracytoplasmic sperm injection (ICSI), gamete intra-fallopian transfer (GIFT), zygote intra-fallopian transfer, gamete and embryo cryopreservation, oocyte and embryo donation and gestational surrogacy.  
According to this definition, ovulation induction (via medication) and intra-uterine insemination (IUI) are not included as ART, but come under the wider classification of medically assisted reproduction.
Since the first successful IVF birth in 1978, there have been over 8 million ART births and roughly 500,000 annually (Fauser 2019)[2].

### Is ART associated with adverse health outcomes?

Interest in epigenetic deregulation as a consequence ART has been sparked by reports of higher rates of birth defects after IVF and ICSI, although maternal factors such as age and lifestyle factors also contribute to this (Ericson & Källén 2001; Hansen et al, 2002; Davies et al, 2012)[3,4,5].

Similarly, the rates of specific conditions such as cerebral palsy, type-1 diabetes and behavioral disorders are higher in IVF conceived children, but could be attributable to higher rates of multiple births (Klemetti et al, 2006)[6].

### Why is ART implicated with epigenetic differences?

A number of studies and meta-analyses have reported higher rates of imprinting disorders for ART as compared to naturally conceived infants (Cox et al, 2002; DeBaun et al, 2003; Maher et al, 2003; Cortessis et al, 2018; Uk et al, 2018)[7-10].
In only a few studies has the potentially confounding effect of maternal age been taken into account (Uk et al, 2018; Hattori et al, 2019)[11-12].
A 2013 meta-analysis taking into consideration maternal age showed that ART conceived infants have a 30% higher rate of birth defects (Hansen et al, 2013)[13], which has been confirmed with a more recent update showing equivalent effects with IVF and ICSI (Zhao et al, 2020)[14].

As ART conceived individuals age, we are beginning to learn about their predisposition to risk of different conditions such as autoimmune, cardiovascular, metabolic and malignancy related maladies.
There are some limitations with this analysis however, such as the substantial improvements in ART procedures over the years which has lead to lower rates of multiple births (Morin & Seli 2018)[15]. 
In the case of childhood cancer, systematic meta-analysis published in 2013 indicates that IVF leads to a 60% higher risk as compared to naturally conceived, however a matched subfertile control group was used in only two of the 25 studies in the meta-analysis (Hargreave et al, 2013)[16].
A later meta-analysis found no significant link between ART and childhood cancer except in the case of cryopreserved embryo transfer, which was associated with a 2.5 fold increased cancer risk, but only when compared to children of fertile women (Hargreave et al, 2019)[17].
It has been argued that ART can increase the risk of cardiometabolic disease, however this is based largely on subclinical features such as small elevation of blood pressure or adiposity for which the association with cardiovascular events and longevity is unclear (Vrooman & Bartolomei 2017)[18].

### What is the link between ART and DNA methylation?

The associations between subfertility/ART and adverse health outcomes including imprinting and other birth defects implies that epigenetic mechanisms may be involved. 
Among these mechanisms, DNA methylation has been the most widely investigated, primarily due to the ease at which it can be assayed in clinical samples.
The focus of methylation analyses has largely been upon imprinted genes, such as H19/IGF2, KCNQ1OT1, PEG3, PEG1, and MEG3 ; but despite this, metaanalysis indicates no consistent association between ART and DNA methylation (Lazaraviciute et al, 2014)[19].
Epigenome-wide methods such as microarray and next generation sequencing have been deployed to identify differences between ART and naturally conceived children, however again the results are inconsistent.

Choufani et al (2015)[20] conducted a 450K array based EWAS on 88 placental samples, including ART with IVF and ISCI.
Importantly this study included different fertile and subfertile naturally conceived control groups.
Estill et al (2016)[21] conducted a 450K array based EWAS on 137 neonatal blood spot samples including IVF and ICSI, including fertile and subfertile naturally conceived control groups.
This study also identified metastable epialleles differentially methylated between conception types such as SPATC1L and DUSP22.
Castillo Fernandes et al (2017)[22] Conducted an enrichment sequencing analysis of 82 CBMC and 98 neonatal whole blood samples, finding just one DMR associated with IVF, at C9orf3.
Hajj et al (2017)[23] analysed 94 cord blood samples from control and ICSI neonates using the 450K array, finding widespread, statistically significant but subtle differences in promoters as well as imprinting control regions.
Lizky et al (2017)[24] analysed placental 450K array data which included 158 participants, only a small number of which were conceived via ART.
This study shows that some of the genes with altered methylation also exhibit differential expression.
Recently, Novakovic et al (2019)[25] performed an EPIC array analysis of neonatal and adult methylation, finding that neonatal epigenetic differences included CHRNE, PRSS16 and TMEM18, but most of these differences did not persist into adulthood.

### What are the current controversies? / What is the aim and rationale of this study?

<TODO>

## Key references:

* https://www.nature.com/articles/s41467-019-11929-9

* https://pubmed.ncbi.nlm.nih.gov/27288894/

## References 

1. Zegers-Hochschild F, Adamson GD, de Mouzon J, et al. International Committee for Monitoring Assisted Reproductive Technology (ICMART) and the World Health Organization (WHO) revised glossary of ART terminology, 2009. Fertil Steril. 2009;92(5):1520-1524. doi:10.1016/j.fertnstert.2009.09.009

2. Fauser BC. Towards the global coverage of a unified registry of IVF outcomes. Reprod Biomed Online. 2019;38(2):133-137. doi:10.1016/j.rbmo.2018.12.001

3. Ericson A, Källén B. Congenital malformations in infants born after IVF: a population-based study. Hum Reprod. 2001;16(3):504-509. doi:10.1093/humrep/16.3.504

4. Hansen M, Kurinczuk JJ, Bower C, Webb S. The risk of major birth defects after intracytoplasmic sperm injection and in vitro fertilization. N Engl J Med. 2002;346(10):725-730. doi:10.1056/NEJMoa010035

5. Davies MJ, Moore VM, Willson KJ, et al. Reproductive technologies and the risk of birth defects. N Engl J Med. 2012;366(19):1803-1813. doi:10.1056/NEJMoa1008095

6. Klemetti R, Sevon T, Gissler M, Hemminki E. Health of children born as a result of in vitro fertilization. Pediatrics. 2006;118: 1819-27.

7. Cox GF, Bu¨rger J, Lip V, Mau UA, Sperling K, Wu BL, et al. Intracytoplasmic sperm injection may increase the risk of imprinting defects. Am J Hum Genet 2002;71:162–4.

8. DeBaun MR, Niemitz EL, Feinberg AP. Association of in vitro fertilization with Beckwith-Wiedemann syndrome and epigenetic alterations of LIT1 and H19. Am J Hum Genet 2003;72:156–60.

9. Maher ER, Brueton LA, Bowdin SC, Luharia A, Cooper W, Cole TR, et al. Beckwith-Wiedemann syndrome and assisted reproduction technology (ART). published erratum appears in J Med Genet 2003;40:304. J Med Genet 2003;40:62–4.

10. Cortessis VK, Azadian M, Buxbaum J, et al. Comprehensive meta-analysis reveals association between multiple imprinting disorders and conception by assisted reproductive technology. J Assist Reprod Genet. 2018;35(6):943-952. doi:10.1007/s10815-018-1173-x

11. Uk A, Collardeau-Frachon S, Scanvion Q, Michon L, Amar E. Assisted Reproductive Technologies and imprinting disorders: Results of a study from a French congenital malformations registry. Eur J Med Genet. 2018;61(9):518-523. doi:10.1016/j.ejmg.2018.05.017

12. Hattori H, Hiura H, Kitamura A, et al. Association of four imprinting disorders and ART. Clin Epigenetics. 2019;11(1):21. Published 2019 Feb 7. doi:10.1186/s13148-019-0623-3

13. Hansen M, Kurinczuk JJ, Milne E, de Klerk N, Bower C. Assisted reproductive technology and birth defects: a systematic review and meta-analysis. Hum Reprod Update. 2013;19(4):330-353. doi:10.1093/humupd/dmt006

14. Zhao J, Yan Y, Huang X, Li Y. Do the children born after assisted reproductive technology have an increased risk of birth defects? A systematic review and meta-analysis. J Matern Fetal Neonatal Med. 2020;33(2):322-333. doi:10.1080/14767058.2018.1488168

15. Morin SJ, Seli E. Assisted Reproductive Technology and Origins of Disease: The Clinical Realities and Implications. Semin Reprod Med. 2018;36(3-04):195-203. doi:10.1055/s-0038-1677048

16. Hargreave M, Jensen A, Toender A, Andersen KK, Kjaer SK. Fertility treatment and childhood cancer risk: a systematic meta-analysis. Fertil Steril. 2013;100(1):150-161. doi:10.1016/j.fertnstert.2013.03.017

17. Hargreave M, Jensen A, Hansen MK, et al. Association Between Fertility Treatment and Cancer Risk in Children. JAMA. 2019;322(22):2203-2210. doi:10.1001/jama.2019.18037

18. Vrooman LA, Bartolomei MS. Can assisted reproductive technologies cause adult-onset disease? Evidence from human and mouse. Reprod Toxicol. 2017;68:72-84. doi:10.1016/j.reprotox.2016.07.015

19. Lazaraviciute G, Kauser M, Bhattacharya S, Haggarty P, Bhattacharya S. A systematic review and meta-analysis of DNA methylation levels and imprinting disorders in children conceived by IVF/ICSI compared with children conceived spontaneously [published correction appears in Hum Reprod Update. 2015 Jul-Aug;21(4):555-7]. Hum Reprod Update. 2014;20(6):840-852. doi:10.1093/humupd/dmu033

20. Choufani S, Turinsky AL, Melamed N, et al. Impact of assisted reproduction, infertility, sex and paternal factors on the placental DNA methylome. Hum Mol Genet. 2019;28(3):372-385. doi:10.1093/hmg/ddy321

21. Estill MS, Bolnick JM, Waterland RA, Bolnick AD, Diamond MP, Krawetz SA. Assisted reproductive technology alters deoxyribonucleic acid methylation profiles in bloodspots of newborn infants. Fertil Steril. 2016;106(3):629-639.e10. doi:10.1016/j.fertnstert.2016.05.006

22. Castillo-Fernandez JE, Loke YJ, Bass-Stringer S, et al. DNA methylation changes at infertility genes in newborn twins conceived by in vitro fertilisation. Genome Med. 2017;9(1):28. Published 2017 Mar 24. doi:10.1186/s13073-017-0413-5

23. El Hajj N, Haertle L, Dittrich M, et al. DNA methylation signatures in cord blood of ICSI children. Hum Reprod. 2017;32(8):1761-1769. doi:10.1093/humrep/dex209

24. Litzky JF, Deyssenroth MA, Everson TM, et al. Placental imprinting variation associated with assisted reproductive technologies and subfertility. Epigenetics. 2017;12(8):653-661. doi:10.1080/15592294.2017.1336589

25. Novakovic B, Lewis S, Halliday J, et al. Assisted reproductive technologies are associated with limited epigenetic variation at birth that largely resolves by adulthood. Nat Commun. 2019;10(1):3922. Published 2019 Sep 2. doi:10.1038/s41467-019-11929-9



## Other papers

https://www.bmj.com/content/321/7258/420?view
Importantly disease risk is influenced not only by conception mode but also maternal age, for example maternal age is a contributing factor to type-1 diabetes onset (Bingley et al, 2000).

Schieve LA, Rasmussen SA, Buck GM, Schendel DE, Reynolds MA, Wright VC. Are children born after assisted reproductive technology at increased risk for adverse health outcomes? Obstet Gynecol. 2004;103:1154-63.

Monk D, Mackay DJG, Eggermann T, Maher ER, Riccio A. Genomic imprinting disorders: lessons on how genome, epigenome and environment interact. Nat Rev Genet. 2019;20(4):235-248. doi:10.1038/s41576-018-0092-0

